---
# tasks file for joe-speedboat.ansible_guacamole

- name: Install epel repository
  yum:
    name: epel-release
    state: present

- name: Install necessary packages
  yum:
    name: '{{ item.package }}'
    state: present
    enablerepo: epel-testing
  with_items: "{{ guacamole_packages_EL }}"
